name: Daily Commit Workflow

on:
  schedule:
    # Runs at 10:30 AM UTC every day
    - cron: '31 10 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Git Config
        run: |
          git config --global user.name "Ashiq-jr"
          git config --global user.email "mohameashiq.syedmustafa@straive.com"
          
      - name: Create and commit file
        run: |
          # Create a timestamp
          echo "Last updated: $(date)" > last_updated.txt
          
          # Add and commit the file
          git add last_updated.txt
          git commit -m "Daily automated commit $(date)"
          git push
