name: Daily Commit Workflow

on:
  schedule:
    - cron: '49 17 * * *'
  workflow_dispatch:

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: mohamedashiq.syedmustafa@straive.com
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          
      - name: Setup Git Config
        run: |
          git config --global user.name "Ashiq-jr"
          git config --global user.email "ashiqjr7@gmail.com"
          
      - name: Create and commit file
        run: |
          echo "Last updated: $(date)" > last_updated.txt
          git add last_updated.txt
          git commit -m "Daily automated commit $(date)"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}  # or use ${{ secrets.YOUR_PAT }}
          branch: ${{ github.ref }}
